version: '3.8'

services:
  iptv-sorter:
    build: .
    container_name: iptv-m3u-sorter
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./saved_playlists:/app/saved_playlists
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - HOST=0.0.0.0
      - PORT=5000
    restart: unless-stopped
    networks:
      - iptv-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  iptv-network:
    driver: bridge
