version: '3.8'

services:
  iptv-sorter:
    build: .
    container_name: iptv-m3u-sorter
    ports:
      - "${HOST_PORT:-5000}:5000"  # Configurable port
    volumes:
      - ./uploads:/app/uploads
      - ./saved_playlists:/app/saved_playlists
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      # Basic Flask settings
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - HOST=0.0.0.0
      - PORT=5000
      
      # Security settings
      - SECRET_KEY=${SECRET_KEY:-}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-52428800}  # 50MB
      - HTTPS_ENABLED=${HTTPS_ENABLED:-false}
      
      # Reverse proxy settings
      - URL_SCHEME=${URL_SCHEME:-http}
      - SERVER_NAME=${SERVER_NAME:-}
      - APP_ROOT=${APP_ROOT:-/}
      
    restart: unless-stopped
    networks:
      - iptv-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Labels for reverse proxy discovery
      - "traefik.enable=true"
      - "traefik.http.routers.iptv-sorter.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.services.iptv-sorter.loadbalancer.server.port=5000"

networks:
  iptv-network:
    driver: bridge
