version: '3.8'

services:
  iptv-sorter:
    image: alexfl1987/iptv-m3u-sorter:latest-stable
    container_name: iptv-m3u-sorter
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
    ports:
      - "${HOST_PORT:-5000}:5000"
    volumes:
      # Nur Datenverzeichnisse mounten - Templates kommen aus dem Docker Image
      - ./uploads:/app/uploads
      - ./saved_playlists:/app/saved_playlists
    environment:
      # Basic Flask settings
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - HOST=0.0.0.0
      - PORT=5000
      
      # Security settings
      - SECRET_KEY=${SECRET_KEY:-}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-52428800}
      - HTTPS_ENABLED=${HTTPS_ENABLED:-false}
      
      # Reverse proxy settings
      - URL_SCHEME=${URL_SCHEME:-http}
      - APP_ROOT=${APP_ROOT:-/}
      
      # Domain für Reverse Proxy Labels
      - DOMAIN=${DOMAIN:-localhost}
      
      # Proxy fix settings
      - PROXY_FIX_X_FOR=${PROXY_FIX_X_FOR:-1}
      - PROXY_FIX_X_PROTO=${PROXY_FIX_X_PROTO:-1}
      - PROXY_FIX_X_HOST=${PROXY_FIX_X_HOST:-1}
      - PROXY_FIX_X_PREFIX=${PROXY_FIX_X_PREFIX:-1}
      
      # Security headers
      - SECURE_HEADERS=${SECURE_HEADERS:-true}
      - ENABLE_CSRF_PROTECTION=${ENABLE_CSRF_PROTECTION:-true}
      
      # Health Check Settings (Optional)
      - ENABLE_FS_HEALTH_CHECKS=${ENABLE_FS_HEALTH_CHECKS:-false}
      
      # Gunicorn settings
      - WORKERS=${WORKERS:-4}
      - WORKER_CLASS=${WORKER_CLASS:-gevent}
      - WORKER_CONNECTIONS=${WORKER_CONNECTIONS:-1000}
      - TIMEOUT=${TIMEOUT:-120}
      
    restart: unless-stopped
    networks:
      - iptv-network
    
    # Vereinfachter Health Check
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ping-simple || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    
    labels:
      # Labels für Reverse Proxy Discovery
      - "traefik.enable=true"
      - "traefik.http.routers.iptv-sorter.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.services.iptv-sorter.loadbalancer.server.port=5000"

networks:
  iptv-network:
    driver: bridge