version: '3.8'

services:
  iptv-sorter:
    image: alexfl1987/iptv-m3u-sorter:latest-stable
    container_name: iptv-m3u-sorter
    user: "${USER_UID:-1000}:${USER_GID:-1000}"
    ports:
      - "${HOST_PORT:-5000}:5000"
    volumes:
      # Only mount data directories - remove templates volume!
      - ./uploads:/app/uploads
      - ./saved_playlists:/app/saved_playlists
      # - ./templates:/app/templates  ❌ Remove this line!
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - HOST=0.0.0.0
      - PORT=5000
      - SECRET_KEY=${SECRET_KEY:-}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-52428800}
      - HTTPS_ENABLED=${HTTPS_ENABLED:-true}
      - URL_SCHEME=${URL_SCHEME:-https}
      - SERVER_NAME=${SERVER_NAME:-}  # Leave empty for localhost access
      - APP_ROOT=${APP_ROOT:-/}
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
    restart: unless-stopped
    networks:
      - iptv-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  iptv-network:
    driver: bridge
